title: Michael Armanious # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Just a curious individual trying to expand my knowledge as much as possible 
  <br><br>
  Interested in Data Science/AI/Machine Learning.
  <br><br>
  Taking many online courses to further my understanding and get experience through projects
  <br><br>
  <a href="https://www.linkedin.com/in/michael-armanious/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
